### ISSUE TITLE
Tags for releases

### ISSUE THREAD

**Issue by minusdavid** [edsilv/biiif#16]
Would it be possible to get git tags for each release which correspond to the npm release?

**Comment by minusdavid** [comment]
If I do "npm show biiif@0.1.9" I see a "gitHead" but the hash doesn't match anything in my biiif clone...

Looks like it's not supposed to be there anyway according to https://github.com/npm/npm/issues/3363 so maybe that's why it doesn't work for me.

**Comment by minusdavid** [comment]
Alternatively, having releases at https://github.com/edsilv/biiif/releases would be useful for checking what npm packages are based on...

**Comment by edsilv** [comment]
I think it makes sense to create releases when publishing to npm - will make sure I do going forward.
