### ISSUE TITLE
Can I use this in serveless?

### ISSUE THREAD

**Issue by rollymaduk** [edsilv/biiif#24]
Hi great work!,please can I use this api  in a serverless context to generate iiif from a remote folder and store my index.json in s3?, thanks.
suggestion: perhaps rather than providing just a destination directory, you can explore an optional callback function that has the JSON returned as payload, for other services to explore.

**Comment by edsilv** [comment]
Thanks! Maybe `index.ts` could return a promise so you can do something like:

```
build('myfolder', 'http://example.com/myfolder').then((indexjson) => {
    // do something with indexjson
});
```

Where `indexjson` is the root-most generated json file (myfolder/index.json)?

**Comment by edsilv** [comment]
Or:

`const indexjson = await build('myfolder', 'http://example.com/myfolder');`

**Comment by edsilv** [comment]
`build` is now entirely async and can be used with `await`, but doesn't return anything as the generated root `index.json` is in the destination directory and easy to find.
